default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flux-capacitor-development

test:
  <<: *default
  database: flux-capacitor-test

production:
  <<: *default
  database: flux-capacitor-production
